- name: Install nexus secrets
  kubernetes.core.helm:
    name: nexus
    namespace: yuuvis
    chart_ref: ../nexus
    kubeconfig_path: "{{ kubeconfig }}"
    create_namespace: True
    wait: true
- name: Install yuuvis-v-api
  kubernetes.core.helm:
    name: yuuvis-v-api
    namespace: yuuvis
    chart_ref: ../api
    kubeconfig_path: "{{ kubeconfig }}"
    create_namespace: True
    wait: true
